name: doctor_appointment_ui
description: A Flutter UI for a doctor appointment application.

environment:
  sdk: '>=2.12.0 <3.0.0' # Adjust the SDK constraint based on your Flutter version

dependencies:
  flutter:
    sdk: flutter
  # Add any additional dependencies your project needs here.

dev_dependencies:
  flutter_test:
    sdk: flutter
