workflows:
  flutter_build:
    name: Flutter Build
    environment:
      flutter: stable

    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.ipa
